### PR TITLE
[REF] rename overloaded functions

### PR DESCRIPTION
**Pull request by robinkeunen**
cf https://github.com/coopiteasy/product-subscription/pull/16/

### CODE REVIEW

**Comment by houssine78** [comment]
@robinkeunen well I don't see the point about this function renaming. what should bring "new" comparing to the previous name. I've no problem for renaming functions but adding "new" in the name seems pointless to me. Or maybe I'm missing something ?

**Comment by robinkeunen** [comment]
It's matching the name of the route :-)

**Comment by houssine78** [comment]
@robinkeunen maybe change the route name too ;)

**Comment by robinkeunen** [comment]
Yeah I said that to Rémy when he created them, it should be `subscription/basic` to comply with common conventions. But I won't change routes now :-)

**Comment by remytms** [comment]
> Yeah I said that to Rémy when he created them, it should be `subscription/basic` to comply with common conventions. But I won't change routes now :-)

This works when the verb can be given via HTTP method in a restfull API.
POST to create
GET to read
PUT to update or replace
DELETE to delete

But that's for a rest full API. Here it's a formular, so I found that having the verb in the route name is needed. Because first call is a GET and with a GET on /subscritpon/basic, we don't get a subscription object in return as rest full API suggest, instead we get a formular.

That's my opinion for now but with good arguments I can change my point of view. :)

**Review by remytms — APPROVED** [review]

**Pull request closed without merging**
